namespace AIScriptToMediaDotNet.Services.ComfyUI;

/// <summary>
/// Represents a ComfyUI workflow prompt.
/// </summary>
public class ComfyuiPrompt
{
    /// <summary>
    /// Gets or sets the workflow nodes as a dictionary.
    /// Each key is a node ID, and the value is the node configuration.
    /// </summary>
    public Dictionary<string, object> Prompt { get; set; } = new();

    /// <summary>
    /// Gets or sets the client ID for tracking this request.
    /// </summary>
    public string ClientId { get; set; } = Guid.NewGuid().ToString("N");
}

/// <summary>
/// Represents the response from queueing a prompt.
/// </summary>
public class ComfyuiQueueResponse
{
    /// <summary>
    /// Gets or sets the prompt ID.
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("prompt_id")]
    public string PromptId { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the number of items in the queue.
    /// </summary>
    [System.Text.Json.Serialization.JsonPropertyName("number")]
    public int Number { get; set; }
}

/// <summary>
/// Represents the status of a generation task.
/// </summary>
public class ComfyuiStatus
{
    /// <summary>
    /// Gets or sets the status type (success, error, etc.).
    /// </summary>
    public string StatusType { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets whether the task is completed.
    /// </summary>
    public bool Completed { get; set; }

    /// <summary>
    /// Gets or sets any error messages.
    /// </summary>
    public List<string> Messages { get; set; } = new();
}

/// <summary>
/// Represents an image generated by ComfyUI.
/// </summary>
public class ComfyuiImage
{
    /// <summary>
    /// Gets or sets the image filename.
    /// </summary>
    public string Filename { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the subfolder path.
    /// </summary>
    public string Subfolder { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the storage type.
    /// </summary>
    public string Type { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the image content type (e.g., "image/png").
    /// </summary>
    public string ContentType { get; set; } = "image/png";
}
